- hosts: <Publicip>
  user: root
  become: yes
  gather_facts: yes
  tasks:
   - name : Download Terraform software
      get_url: https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_amd64.zip?_ga=2.196228268.1257085564.1503566885497200374.1503566885 dest=/root/Downloads
      
   - name: unarchivng terraform downloaded software
       unarchive: src=/root/Downloads/terraform_0.10.0_linux_amd64.zip dest=/root/Downloads copy=no


# Configure the AWS Provider

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "us-east-1"
}


provisioner  "remote-exec" {
  inline = [
    "chmod +x /etc/ansible/playbooks/s3copy.yml",
        "cd /etc/ansible/plabooks/",
        "ansible-playbook s3copy.yml"
   ]
}
   
