---
- hosts: testproject
  user: root
  become: true
  gather_facts: no
  vars_prompt:
      - name: pkg
        prompt: enter image name
        private: no

      - name: pkg1
        prompt: enter tag name
        private: no

  tasks:
   - name: aws configure
     expect:
       command: /bin/bash -c "aws configure"
       timeout: 
       responses:
         AWS Access Key ID*: ''
         AWS Secret Access Key*: ''
         Default region name*: ''
         Default output format*: ''
       echo: yes

#   - name: create ecr login
#     command: aws ecr get-login

#   - name:  evaluate login by passing key
#     script: eval $(aws ecr get-login | sed 's|https://||')

   - name: ECR login
     shell: "$(aws ecr get-login --region eu-west-2)"

   - name: list of docker images
     command: docker images
     register: result 
   - debug: var=result 


#   - name: Log into private registry and force re-authorization
#     docker_login:
#       registry: https://635991583802.dkr.ecr.us-west-2.amazonaws.com/jaas1603/coreapp
#       username: admin
#       password: Admin@1234
#       reauthorize: yes

   - name: create tag and push to repository 
     docker_image: 
       name: "{{ pkg }}"
       repository: 635991583802.dkr.ecr.us-west-2.amazonaws.com/devopsrepo
       tag: "{{ pkg1 }}"
       push: yes
     register: result
   - debug: var=result     
